---
- name: "Create Runner Config volume"
  community.docker.docker_volume:
    name: "{{ install_gitlab_runner_config_volume }}"
    state: "present"

- name: "Import toml config file"
  ansible.builtin.template:
    src: "templates/config.toml.j2"
    dest: "/var/lib/docker/volumes/{{ install_gitlab_runner_config_volume }}/_data/config.toml"
    owner: "root"
    group: "root"
    mode: "0700"

- name: "Install GitLab Runner"
  community.docker.docker_container:
    name: "{{ install_gitlab_runner_name }}"
    image: "{{ install_gitlab_runner_image }}"
    state: "started"
    recreate: false
    restart_policy: "always"
    devices:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ install_gitlab_runner_config_volume }}:/etc/gitlab-runner"
