---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_gitlab_runner"
      tags:
        - "labocbz.install_gitlab_runner"
      vars:
        install_gitlab_runner_concurrent: "{{ inv_install_gitlab_runner_concurrent }}"
        install_gitlab_runner_session_timeout: "{{ inv_install_gitlab_runner_session_timeout }}"
        install_gitlab_runner_image: "{{ inv_install_gitlab_runner_image }}"
        install_gitlab_runner_name: "{{ inv_install_gitlab_runner_name }}"
        install_gitlab_runner_url: "{{ inv_install_gitlab_runner_url }}"
        install_gitlab_runner_token: "{{ inv_install_gitlab_runner_token }}"
        install_gitlab_runner_config_volume: "{{ inv_install_gitlab_runner_config_volume }}"
        install_gitlab_runner_docker_tls_verify: "{{ inv_install_gitlab_runner_docker_tls_verify }}"
        install_gitlab_runner_docker_image: "{{ inv_install_gitlab_runner_docker_image }}"
      ansible.builtin.include_role:
        name: "labocbz.install_gitlab_runner"
