---
- name: "Converge"
  hosts: "cicd-docker-dind"
  tasks:

    - name: "Include labocbz.install_gitlab_runner"
      tags:
        - "labocbz.install_gitlab_runner"
      vars:
        install_gitlab_runner__concurrent: "{{ inv_install_gitlab_runner__concurrent }}"
        install_gitlab_runner__session_timeout: "{{ inv_install_gitlab_runner__session_timeout }}"
        install_gitlab_runner__image: "{{ inv_install_gitlab_runner__image }}"
        install_gitlab_runner__name: "{{ inv_install_gitlab_runner__name }}"
        install_gitlab_runner__url: "{{ inv_install_gitlab_runner__url }}"
        install_gitlab_runner__token: "{{ inv_install_gitlab_runner__token }}"
        install_gitlab_runner__config_volume: "{{ inv_install_gitlab_runner__config_volume }}"
        install_gitlab_runner__docker_tls_verify: "{{ inv_install_gitlab_runner__docker_tls_verify }}"
        install_gitlab_runner__docker_image: "{{ inv_install_gitlab_runner__docker_image }}"
        install_gitlab_runner__pull_policy: "{{ inv_install_gitlab_runner__pull_policy }}"
        install_gitlab_runner__force_register: "{{ inv_install_gitlab_runner__force_register }}"
        install_gitlab_runner__docker_privileged: "{{ inv_install_gitlab_runner__docker_privileged }}"
      ansible.builtin.include_role:
        name: "labocbz.install_gitlab_runner"
